source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Configurable_Example', :exclusive => true do
  pod "Configurable", :path => "../"
end

target 'Configurable_Tests', :exclusive => true do
  pod "Configurable", :path => "../"

  
end
